"""VocabForge — vocabulary data (IPA, POS, meanings, reflections, etc.)"""

IPA_DATA = {
    "block": "/blɒk/", "career": "/kəˈrɪə/", "client": "/ˈklaɪənt/",
    "communicate": "/kəˈmjuːnɪkeɪt/", "curious": "/ˈkjʊəriəs/",
    "difference": "/ˈdɪfərəns/", "disappear": "/ˌdɪsəˈpɪə/",
    "district": "/ˈdɪstrɪkt/", "drop": "/drɒp/", "either": "/ˈaɪðə/",
    "exist": "/ɪɡˈzɪst/", "financial": "/faɪˈnænʃəl/", "guard": "/ɡɑːd/",
    "let": "/let/", "machine": "/məˈʃiːn/", "matter": "/ˈmætə/",
    "owe": "/əʊ/", "police": "/pəˈliːs/", "private": "/ˈpraɪvɪt/",
    "probably": "/ˈprɒbəbli/", "rat": "/ræt/", "recognize": "/ˈrekəɡnaɪz/",
    "represent": "/ˌreprɪˈzent/", "role": "/rəʊl/", "scene": "/siːn/",
    "search": "/sɜːtʃ/", "security": "/sɪˈkjʊərɪti/", "service": "/ˈsɜːvɪs/",
    "sort": "/sɔːt/", "target": "/ˈtɑːɡɪt/", "track": "/træk/",
    "trade": "/treɪd/", "western": "/ˈwestən/", "whole": "/həʊl/",
    "active": "/ˈæktɪv/", "direct": "/daɪˈrekt/", "escape": "/ɪˈskeɪp/",
    "explain": "/ɪkˈspleɪn/", "forward": "/ˈfɔːwəd/", "lead": "/liːd/",
    "lie": "/laɪ/", "partner": "/ˈpɑːtnə/", "piece": "/piːs/",
    "pull": "/pʊl/", "report": "/rɪˈpɔːt/", "separate": "/ˈsepərət/",
    "sight": "/saɪt/", "unusual": "/ʌnˈjuːʒuəl/",
    "connect": "/kəˈnekt/", "convince": "/kənˈvɪns/", "innocent": "/ˈɪnəsnt/",
    "concert": "/ˈkɒnsət/", "event": "/ɪˈvent/",
    "tower": "/ˈtaʊə/", "rule": "/ruːl/", "stick": "/stɪk/",
    "wheel": "/wiːl/", "print": "/prɪnt/", "hundred": "/ˈhʌndrəd/",
    "arrange": "/əˈreɪndʒ/", "basic": "/ˈbeɪsɪk/", "bury": "/ˈberi/",
    "surprise": "/səˈpraɪz/", "mile": "/maɪl/",
}

MEANING_DATA = {
    "block": "阻挡；封锁；街区；挡住",
    "career": "职业；生涯；事业",
    "client": "客户；委托人；顾客",
    "communicate": "交流；沟通；通讯；通道",
    "curious": "好奇的；求知欲强的",
    "difference": "差异；不同；区别",
    "disappear": "消失；不见",
    "district": "地区；区域；行政区",
    "drop": "放下；放弃；掉落；扔掉",
    "either": "两者之一；也",
    "exist": "存在；生存",
    "financial": "财政的；金融的；财务",
    "guard": "守卫；警卫；保护",
    "let": "让；允许；放出",
    "machine": "机器；机械",
    "matter": "事情；问题；物质；要紧；重要；关系",
    "owe": "欠；归功于",
    "police": "警察；警方",
    "private": "私人的；私密的；隐私",
    "probably": "很可能；大概",
    "rat": "老鼠；告密者；出卖",
    "recognize": "认出；认识到",
    "represent": "代表；表示",
    "role": "角色；作用",
    "scene": "场景；现场；景象",
    "search": "搜索；搜寻；搜身",
    "security": "安全；安保；证券",
    "service": "服务；服役",
    "sort": "种类；分类；整理",
    "target": "目标；对象",
    "track": "追踪；轨道；踪迹",
    "trade": "贸易；交易",
    "western": "西方的；西部的",
    "whole": "整个的；全部的；整个",
    "active": "活跃的；有效的",
    "direct": "直接的；指导；导演",
    "escape": "逃跑；逃避",
    "explain": "解释；说明",
    "forward": "向前的；转交；期待",
    "lead": "领导；带领；线索",
    "lie": "说谎；躺；位于；骗",
    "partner": "伙伴；搭档；合伙人",
    "piece": "片；块；件；碎片",
    "pull": "拉；拖；吸引",
    "report": "报告；报道",
    "separate": "分开的；单独的；分离",
    "sight": "视力；视野；景象",
    "unusual": "不寻常的；独特的",
    "connect": "连接；联系；相连",
    "convince": "说服；使确信",
    "innocent": "无辜的；天真的",
    "tower": "塔；高楼",
    "rule": "规则；统治；规矩",
    "stick": "棍子；粘住；坚持",
    "wheel": "轮子；车轮",
    "concert": "音乐会；一致",
    "event": "事件；活动",
    "print": "印刷；打印；印记；指纹",
    "hundred": "一百；数百；几百",
    "arrange": "安排；整理；筹备",
    "basic": "基本的；基础的",
    "bury": "埋葬；掩埋",
    "surprise": "惊讶；惊喜；出乎意料",
    "mile": "英里",
}

POS_DATA = {
    "block": "v./n", "career": "n", "client": "n",
    "communicate": "v", "curious": "adj",
    "difference": "n", "disappear": "v",
    "district": "n", "drop": "v./n", "either": "adv./pron",
    "exist": "v", "financial": "adj", "guard": "n./v",
    "let": "v", "machine": "n", "matter": "n./v",
    "owe": "v", "police": "n", "private": "adj",
    "probably": "adv", "rat": "n./v", "recognize": "v",
    "represent": "v", "role": "n", "scene": "n",
    "search": "v./n", "security": "n", "service": "n",
    "sort": "n./v", "target": "n./v", "track": "v./n",
    "trade": "n./v", "western": "adj", "whole": "adj./n",
    "active": "adj", "direct": "adj./v", "escape": "v./n",
    "explain": "v", "forward": "adv./adj", "lead": "v./n",
    "lie": "v./n", "partner": "n", "piece": "n",
    "pull": "v", "report": "v./n", "separate": "adj./v",
    "sight": "n", "unusual": "adj",
    "connect": "v", "convince": "v", "innocent": "adj",
    "concert": "n", "event": "n",
    "tower": "n", "rule": "n./v", "stick": "v./n",
    "wheel": "n", "print": "v./n", "hundred": "num",
    "arrange": "v", "basic": "adj", "bury": "v",
    "surprise": "n./v", "mile": "n",
}

REFLECTION_DATA = {
    "connect": "Finch说『When you find that one person who connects you to the world』——connect接to/with，不及物时用connect to，全剧核心词。",
    "machine": "注意ch发/ʃ/而非/tʃ/！Finch造了The Machine，搭配operate/monitor/build the machine。",
    "watch": "『You are being watched.』被动语态经典。watch强调专注看，比see/look更主动。",
    "search": "search for = 寻找；search sb = 搜身。剧中警察常说search warrant搜查令。",
    "target": "on target = 正轨；target date = 目标日期。谁是猎人谁是猎物？",
    "track": "track down = 追查到；keep track of = 跟踪。注意track和trace的区别。",
    "security": "social security number社保号是剧情关键。Finch的公司叫Security——讽刺。",
    "private": "I'm a really private person——Finch台词。private强调个人隐私，反义public。",
    "police": "集合名词谓语用复数！the police are...。正义往往在system之外。",
    "protect": "protect sb from/against sth。词根tect=遮盖。全剧的道德基石。",
    "kill": "Reese的past，Finch引导他不再kill。这个词带着沉重的情感色彩。",
    "save": "区别于rescue（紧急救援），save更广泛。We're not killing, we're saving。",
    "government": "the government作主语用单数。who watches the watchmen？",
    "numbers": "the numbers = 社保号。a number of + 复数谓语=许多。",
    "past": "past作形容词：past experience；作名词：in the past。每个人都无法escape past。",
    "help": "can't help doing = 忍不住；help sb with sth。施助者也是被救赎者。",
    "wrong": "go wrong = 出问题。没有一个绝对的wrong——灰色地带是POI的底色。",
    "chance": "by chance = 偶然。Finch给了Reese a second chance——代表希望。",
    "trust": "trust sb = 信任；trust in sb = 信赖。全剧最动人的character arc。",
    "choice": "make a choice; have no choice but to do。『You have a decision to make.』",
    "leave": "leave sb/sth behind = 抛下。Reese被leave for dead——故事的起点。",
    "find": "find sb doing = 发现某人正在做；find out = 查明。两人都在find。",
    "need": "need doing = 需要被做（主动表被动）。『You need a purpose.』——改变一生的话。",
    "tell": "tell sb about sth; tell apart = 区分。『I said I'd tell you the truth. Didn't say you'd like it.』",
    "follow": "follow sb = 跟踪。as follows = 如下。Reese的日常工作就是follow。",
    "city": "纽约是POI的third character。Finch说Eight million people——又大又孤独。",
    "door": "answer the door = 开门应客。每扇door背后都有故事。",
    "case": "in case of = 以防。每集都是一个new case。",
    "man": "man的复数men。Person of Interest中的person就是man/woman。",
    "day": "the other day = 前几天。Every day a new number, a new chance。",
    "way": "on the way = 在路上；by the way = 顺便。Different ways, same goal。",
    "face": "face to face; in the face of。face做动词=勇敢面对。",
    "hear": "hear sb doing = 听到某人正在做。Finch真正会hear。",
    "word": "have a word with = 谈谈；keep one's word = 守信。Finch每个word精心挑选。",
    "hand": "on the one hand...on the other hand。Reese's hands can kill or save。",
    "look": "look forward to (to是介词！)。Reese的look是observe。",
    "back": "back and forth; back sb up = 支持。都想go back——时间不等人。",
    "think": "think of/about; think highly of。Finch thinks, Reese acts——互补。",
    "know": "know sb/sth; be known as/for。『You don't know anything.』『I know everything.』",
    "care": "care about = 在乎；take care of。在cold NYC中care about strangers——人性。",
    "people": "people本身就是复数！a person单数。every people has a story。",
    "bad": "go bad = 变坏。剧中不是black and white——poetic irony。",
    "good": "do good; for good = 永久地。在grey world里做good。",
    "life": "come to life = 苏醒。every life matters——Finch的初衷。",
    "ask": "ask for = 要求。『Don't ask.』——Finch最常用的回答。",
    "answer": "answer for = 负责。Machine唯一不能answer的是right和wrong的边界。",
    "call": "call off = 取消。Reese's phone call意味着danger或salvation。",
    "come": "come across = 偶遇；come up with = 想出。when machine comes for you。",
    "walk": "walk into = 走进；walk out on = 抛弃。Reese walks like a predator。",
    "talk": "talk into = 说服；talk out of = 劝阻。Finch talks, Reese acts。",
    "take": "take care of; take for granted。关于take和give的balance。",
    "make": "make a difference; make sense。每个人都在make choices。",
    "long": "before long = 不久；as long as = 只要；no longer = 不再。漫长的wait但值得。",
    "right": "right away = 立刻。『Doing the right thing in a wrong world.』——核心命题。",
    "check": "check in = 入住/汇报；check out = 退房/核实。Every action需要double-check。",
    "agent": "double agent = 双重间谍。Reese was CIA agent——now a free agent of justice。",
    "identify": "identify with = 认同；identify as = 认定为。Machine's core function。",
    "believe": "believe in = 信仰；make believe = 假装。Sometimes saving = believing。",
    "truth": "to tell the truth。truth往往比想象的更complicated。",
    "simple": "simple的副词是simply！表面simple背后complex——POI的叙事哲学。",
    "done": "have done with = 结束。当all is done——there's always one more。",
    "belong": "belong to = 属于（无被动！）。Reese didn't belong anywhere——until Finch。",
    "reason": "reason for (不是of!) = 原因。Finch's every decision is logical。",
    "listen": "listen to (必须接to!)。In noisy NYC, listen > speak。",
    "clear": "clear up = 澄清。when clues become clear——truth is chilling。",
    "start": "start with = 以……开始。Every rescue starts with a number。",
    "enough": "enough放adj后：good enough。『Never enough.』——their destiny。",
    "somebody": "someone/大人物(反nobody)。Everyone is somebody。",
    "lot": "a lot of = 许多。a lot of stories, a lot of secrets。",
    "point": "point of view = 视角；point out = 指出。You can't save everyone, but you can try。",
    "always": "always用于一般现在时表频率。Reese's phone always rings。",
    "hold": "hold on = 坚持/稍等；hold up = 耽搁。In danger, hold on = victory。",
    "turn": "turn into = 变成；turn out = 结果是。Every turn = new danger or hope。",
    "old": "grow old = 变老。『Old habits die hard.』——past always catches up。",
    "give": "give up = 放弃；give in = 屈服。Reese和Finch give hope。",
    "stop": "stop doing = 停止做；stop to do = 停下来去做。Reese says stop = danger over。",
    "own": "on one's own = 独自。每个人都自己的destiny和path。",
    "keep": "keep doing = 一直做；keep up with = 跟上。Finch keeps secrets, Reese keeps watch。",
    "wait": "wait for = 等待。Most of surveillance is wait。",
    "build": "build up = 积累。Finch built the machine——machine built this story。",
    "see": "see sb doing = 看到某人正在做。See something, do something。",
    "best": "do one's best = 尽全力。Everyone does their best。",
    "new": "new to = 对……不熟悉。Every day a new beginning。",
    "everything": "everything抽象 / every thing具体。After losing everything——a purpose。",
    "let": "let sb do (无to！)；let down = 让人失望。全剧最高频——简单但有力。",
    "service": "注意ser-词根=服务。Reese从military service到serving people。",
    "client": "client ≠ customer！client是专业服务客户。Finch的clients是需要帮助的人。",
    "print": "fingerprint指纹；fine print小字。print v/n。print out打印。",
    "scene": "crime scene犯罪现场；behind the scenes幕后。S01E01 opening scene经典。",
    "owe": "owe sb sth = 欠。Reese欠的不是money——是a second chance。",
    "block": "block the way挡路；mental block心理障碍。Reese在重新学习rules。",
    "career": "career强调职业路径(≠job)。past defines who they are。",
    "difference": "make a difference高频短语！在世界上make a difference。",
    "disappear": "dis-否定+appear。Reese disappeared——declared dead, in shadows。",
    "drop": "drop by顺便拜访；drop off放下；drop out退学。『Drop your weapon.』",
    "either": "either...or...二者选一；me either我也是(否定句)。发/aɪ/或/iː/均可。",
    "exist": "exist不及物无被动！Machine knows everyone exists——政府deny its existence。",
    "guard": "guard against防范；on guard警惕。Reese was guard dog→became guardian。",
    "matter": "作v: It doesn't matter. 作n: as a matter of fact。but everything matters。",
    "probably": "80%可能性>maybe 50%。注意拼写probAbly不是probBly！",
    "rat": "rat on sb告发；smell a rat感觉不对。subway rat + informant双关。",
    "recognize": "re-再+cogn知道+ize。注意recognize(美)/recognise(英)。",
    "represent": "re-再+present。re-前缀：/riː/表again, /rɪ/表强调。",
    "role": "play a role in; role model。Reese从killer到protector——character arc。",
    "sort": "sort of有点(口语高频)；sort out解决。Machine sorts irrelevant from relevant。",
    "whole": "the whole + n.整个；as a whole总体上。whole /həʊl/ ≠ whale /weɪl/。",
    "active": "take an active part in。Reese from inactive to active。",
    "direct": "adj直接的/v指导。Finch directs from behind the scenes。",
    "escape": "escape from逃脱；narrow escape九死一生。escape及物不加from。",
    "explain": "explain to sb(不是explain sb!)。Finch rarely explains——mystery layer。",
    "forward": "look forward to(to是介词！)。两人couldn't look forward until they found each other。",
    "lead": "lead to导致；take the lead带头。过去式led。Reese leads action。",
    "lie": "两个lie：说谎(lied-lying) vs 躺(lay-lain)。life built on lies。",
    "partner": "partner in crime = 搭档（口语）。最unlikely partnership。",
    "piece": "a piece of; piece together拼凑。Every clue is a piece。",
    "pull": "pull over靠边停车；pull through挺过去。push vs pull。",
    "report": "report to sb汇报。truth is never in the report。",
    "separate": "separate from分开。注意拼写中间par不是per！",
    "sight": "catch sight of突然看到；out of sight看不见。10,000 eyes nothing out of sight。",
    "unusual": "un-否定+usual。nothing unusual——Machine sees the unusual。",
    "convince": "convince sb of sth; be convinced that。Finch logic vs Reese action。",
    "innocent": "play innocent装无辜。发音/ˈɪnəsnt/ sc不发音。",
    "concert": "in concert with与……一致。行动需要像orchestra精准。",
    "event": "current events时事；in the event of如果。Machine只关注relevant events。",
    "tower": "towers = 双子塔。power的象征+surveillance制高点。",
    "rule": "as a rule通常；rule out排除。Reese给Fusco规则但自己no rule。",
    "stick": "stick to坚持；stick with跟随。过去式stuck。从lone wolves到team。",
    "wheel": "behind the wheel开车。always behind the wheel。",
    "hundred": "hundreds of = 数百（加s！）。Finch追求百分百certainty。",
    "arrange": "arrange for sb to do。Finch arranges everything。",
    "basic": "basic training; basic needs。剧情complex但premise simple。",
    "bury": "bury the hatchet言和；be buried in埋头于。truth always surfaces。",
    "surprise": "in surprise惊讶；take by surprise突袭。人性always unpredictable。",
    "mile": "miss by a mile差远了；go extra mile加倍努力。Every mile has a story。",
    "police": "集合名词谓语复数：the police are。正义往往在system之外。",
}

MNEMONIC_MAP = {
    "block": "b(被) + lock(锁) → 被锁住 → 阻挡/街区",
    "career": "car(车) + eer → 车在轨道上跑 → 职业生涯",
    "client": "cli(可联想clinic诊所) + ent(人) → 来诊所的人 → 客户",
    "communicate": "com(共同) + muni(服务) + icate → 共同服务 → 沟通交流",
    "curious": "cur(关心) + ious(形容词) → 关心的 → 好奇的",
    "difference": "di(分开) + fer(带来) + ence → 带来不同 → 差异",
    "disappear": "dis(不) + appear(出现) → 不出现 → 消失",
    "district": "di(加强) + strict(严格的) → 严格划分 → 区域/行政区",
    "drop": "联想「水滴落下」→ 掉落/放下",
    "either": "e + i + ther → 注意 ei 发/aɪ/音 → 两者之一",
    "exist": "ex(出) + ist(站) → 站出来 → 存在",
    "financial": "finance(财务) + ial(形容词) → 金融的；财务的",
    "guard": "gate(门) + ward(看守) → 门口看守 → 守卫",
    "let": "最简单动词之一 → 让/允许（let sb do sth）",
    "machine": "mach(机械) + ine → 机器（注意ch发/ʃ/）",
    "matter": "mat(垫子) + ter → 垫子上的东西 → 事情/物质/要紧",
    "owe": "发音类似「哦」→ 欠钱时发出的声音 → 欠；归功于",
    "police": "policy(政策) → 执行政策的人 → 警察",
    "private": "priv(私有的) + ate → 私人的；私密的",
    "probably": "prob(证明) + ably(能) → 能被证明的 → 很可能",
    "rat": "老鼠；告密者（rat on sb 告发某人）",
    "recognize": "re(再) + cogn(知道) + ize → 再次知道 → 认出；认识到",
    "represent": "re(再) + present(呈现) → 再次呈现 → 代表",
    "role": "联想 roll(卷) → 剧本卷起来 → 角色/作用",
    "scene": "发音同seen(被看到) → 看到的 → 场景/现场",
    "search": "sea(海) + rch → 在茫茫大海中搜索 → 搜寻",
    "security": "secure(安全的) + ity(名词) → 安全；安保",
    "service": "serve(服务) + ice → 服务；服役",
    "sort": "a sort of = 一种；sort out = 整理好",
    "target": "tar(焦油) + get(得到) → 用焦油做标记 → 目标",
    "track": "火车轨道 → 轨道/追踪（track down 追查到）",
    "trade": "t + rade 联想 grade(等级) → 贸易分等级 → 交易/贸易",
    "western": "west(西) + ern(形容词) → 西方的",
    "whole": "区分whole(整个)和whale(鲸鱼) → a 是动物，o 是全部",
    "active": "act(行动) + ive(形容词) → 行动的 → 活跃的",
    "direct": "di(加强) + rect(直的) → 使变直 → 指导/直接的",
    "escape": "es(出) + cape(斗篷) → 披上斗篷溜出去 → 逃跑",
    "explain": "ex(出) + plain(清楚) → 说清楚 → 解释/说明",
    "forward": "for(向前) + ward(方向) → 向前；期待（look forward to）",
    "lead": "l + ead 联想 read(读) → 领导阅读 → 引领/领导",
    "lie": "lie 有双重含义：说谎 / 躺。lie to sb 对某人说谎",
    "partner": "part(部分) + ner(人) → 组成一部分的人 → 搭档/伙伴",
    "piece": "pi 联想π + ece → 一片π → 一片/一块（a piece of）",
    "pull": "对比 push(推) → pull(拉)，一个推一个拉",
    "report": "re(回) + port(带) → 带回来 → 报告/报道",
    "separate": "se(分开) + par(准备) + ate → 分别准备 → 分开的/分离",
    "sight": "see(看) 变成 sight(视野/景象) → 名词形式",
    "unusual": "un(不) + usual(通常的) → 不寻常的",
    "connect": "con(一起) + nect(绑) → 绑在一起 → 连接",
    "convince": "con(加强) + vince(征服) → 用言语征服 → 说服",
    "innocent": "in(不) + noc(伤害) + ent → 不伤害人的 → 无辜的",
    "tower": "联想 town(城镇) → 城镇里有高塔 → 塔/高楼",
    "rule": "ruler(统治者) → rule 是规则/统治",
    "stick": "stick to = 坚持；stick with = 粘住",
    "wheel": "wheel(轮子), wheelchair(轮椅)",
    "concert": "con(一起) + cert(确定) → 一致 → 音乐会",
    "event": "e(出) + vent(来) → 出来的事 → 事件",
    "print": "联想 printer(打印机) → 印刷/打印",
    "hundred": "hun(百) + dred → 一百；数百",
    "arrange": "ar(加强) + range(排列) → 安排/整理",
    "basic": "base(基础) + ic → 基本的",
    "bury": "联想 bur(燃烧)y → 埋葬在地下",
    "surprise": "sur(超过) + prise(拿) → 出人意料 → 惊喜/惊讶",
    "mile": "一英里 ≈ 1.6 公里",
}

ROOT_DATA = {
    "connect": "con- (共同) + nect (绑)",
    "block": "源自古英语，原意为'圆木'",
    "career": "car (车) + eer (人) → 车行之路 → 生涯",
    "client": "cli- (倾斜) + ent (人) → 依靠的人 → 客户",
    "communicate": "com- (共同) + muni (服务) + -icate (动词后缀)",
    "curious": "cur- (关心) + -ious (形容词后缀)",
    "difference": "dis- (分开) + fer (带来) + -ence (名词后缀)",
    "disappear": "dis- (不) + appear (出现)",
    "district": "di- (加强) + strict (严格的) → 严格划分的区域",
    "drop": "源自中古英语drope，水滴落下",
    "either": "e- (强调) + either (古英语ægther)",
    "exist": "ex- (出) + ist (站) → 站出来 → 存在",
    "financial": "finance (财务) + -ial (形容词后缀)",
    "guard": "gard- (保护) → 守卫",
    "let": "古英语lǣtan，意为'允许'",
    "machine": "mach- (机械) + -ine (名词后缀)",
    "matter": "mater- (物质/母亲) + -ter → 物质/事情",
    "owe": "古英语āgan'拥有'，衍生出'欠'",
    "police": "polis (城市/城邦) → 城市管理者 → 警察",
    "private": "priv- (私有的) + -ate (形容词后缀)",
    "probably": "prob- (证明/测试) + -ably (可能地)",
    "rat": "拟声词，模仿老鼠吱吱声",
    "recognize": "re- (再) + cogn (知道) + -ize (动词后缀)",
    "represent": "re- (再) + present (呈现) → 再次呈现 → 代表",
    "role": "rol- (卷) → 卷轴上的角色",
    "scene": "skēnē (希腊语'帐篷') → 舞台 → 场景",
    "search": "cir- (环绕) → 古法语cerchier'搜寻'",
    "security": "se- (无) + cur- (担心) + -ity (名词后缀)",
    "service": "serv- (服务) + -ice (名词后缀)",
    "sort": "sors (拉丁语'命运') → 分类/种类",
    "target": "targe (古法语'盾牌') → 靶心 → 目标",
    "track": "trac- (拉/拖) → 留下的痕迹 → 轨道",
    "trade": "tread (行走) → 行走的路 → 贸易之路",
    "western": "west (西) + -ern (形容词后缀)",
    "whole": "hal (古英语'健康/完整') → 整个的",
    "active": "act (行动) + -ive (形容词后缀)",
    "direct": "di- (加强) + rect (直的) → 使变直",
    "escape": "ex- (出) + cape (斗篷) → 披上斗篷溜走",
    "explain": "ex- (出) + plain (清楚) → 说清楚",
    "forward": "fore- (前) + -ward (方向) → 向前",
    "lead": "lǣdan (古英语'引导') → 领导/带领",
    "lie": "古英语lēogan'说谎' / licgan'躺'",
    "partner": "part (部分) + -ner (人) → 合伙人",
    "piece": "古法语piece'一片/一块'",
    "pull": "古英语pullian'拉/拽'",
    "report": "re- (回) + port (带) → 带回来 → 报告",
    "separate": "se- (分开) + par (准备) + -ate → 分开",
    "sight": "see (看) 的名词形式 → 视野/景象",
    "unusual": "un- (不) + usual (通常的)",
    "convince": "con- (加强) + vince (征服) → 言语征服",
    "innocent": "in- (不) + noc (伤害) + -ent → 不伤害人的",
    "concert": "con- (一起) + cert (确定) → 一致 → 音乐会",
    "event": "e- (出) + vent (来) → 出现的事 → 事件",
    "tower": "turris (拉丁语'塔') → 高塔",
    "rule": "reg- (统治) → 规则/统治",
    "stick": "stic- (刺) → 刺入 → 粘住/坚持",
    "wheel": "hweogol (古英语'轮子')",
    "print": "premere (拉丁语'压') → 压印 → 印刷",
    "hundred": "hun (百) + dred → 一百",
    "arrange": "ar- (加强) + range (排列) → 安排",
    "basic": "base (基础) + -ic (形容词后缀)",
    "bury": "byrgan (古英语'埋葬')",
    "surprise": "sur- (超过) + prise (拿) → 出乎意料",
    "mile": "mille (拉丁语'一千') → 一千步的距离",
}

COLLOCATION_DATA = {
    "connect": "connect A to/with B、connect to the Internet",
    "block": "block the way、block sb from doing、road block",
    "career": "career path、career change、political career",
    "client": "client base、meet with a client、corporate client",
    "communicate": "communicate with sb、communicate effectively",
    "curious": "curious about、curious look、curious fact",
    "difference": "make a difference、tell the difference、spot the difference",
    "disappear": "disappear from、disappear without trace、make sth disappear",
    "district": "business district、school district、district attorney",
    "drop": "drop by、drop off、drop out、drop the case",
    "either": "either...or...、either side、me either",
    "exist": "exist in、exist on、cease to exist",
    "financial": "financial crisis、financial support、financial advisor",
    "guard": "guard against、on guard、security guard、guard dog",
    "let": "let go、let sb do、let down、let alone",
    "machine": "washing machine、vending machine、by the machine",
    "matter": "as a matter of fact、no matter、what's the matter",
    "owe": "owe sth to sb、owe it to yourself、owe an apology",
    "police": "police officer、police station、call the police",
    "private": "private life、private property、private investigator",
    "probably": "most probably、probably not、will probably",
    "rat": "rat race、smell a rat、rat on sb",
    "recognize": "recognize as、recognize the importance、fail to recognize",
    "represent": "represent sb、represent a challenge、represent the best",
    "role": "play a role in、role model、leading role",
    "scene": "crime scene、scene of the accident、behind the scenes",
    "search": "search for、in search of、search engine、search warrant",
    "security": "security system、national security、security guard",
    "service": "customer service、public service、service sector",
    "sort": "sort of、sort out、all sorts of",
    "target": "target audience、on target、target date",
    "track": "track down、keep track of、on track、lose track",
    "trade": "trade with、trade off、foreign trade、trade secret",
    "western": "western world、western culture、western style",
    "whole": "the whole world、as a whole、on the whole",
    "active": "active role、active participation、active member",
    "direct": "direct result、direct object、direct sb to、direct flight",
    "escape": "escape from、escape notice、fire escape、narrow escape",
    "explain": "explain to sb、explain why、explain the situation",
    "forward": "look forward to、move forward、put forward、come forward",
    "lead": "lead to、lead the way、take the lead、lead a team",
    "lie": "lie to sb、lie about、white lie、lay/lain (变化)",
    "partner": "business partner、dance partner、partner in crime",
    "piece": "a piece of、piece together、piece of advice、in pieces",
    "pull": "pull out、pull up、pull over、pull yourself together",
    "report": "report on、news report、report card、report to",
    "separate": "separate from、keep separate、separate ways",
    "sight": "in sight、out of sight、catch sight of、at first sight",
    "unusual": "unusual for、unusual sight、nothing unusual",
    "convince": "convince sb to do、convince sb of、be convinced",
    "innocent": "innocent people、innocent until proven、innocent look",
    "concert": "go to a concert、in concert with、concert hall",
    "event": "in any event、current events、special event、social event",
    "tower": "control tower、Eiffel Tower、tower above/over",
    "rule": "as a rule、rule out、ground rules、break the rules",
    "stick": "stick to、stick with、stick out、stick together",
    "wheel": "behind the wheel、steering wheel、wheels of justice",
    "print": "print out、in print、fine print、fingerprint",
    "hundred": "hundreds of、a hundred percent、one hundred",
    "arrange": "arrange for、arrange a meeting、arrange to do",
    "basic": "basic needs、basic principle、basic skills、basic training",
    "bury": "bury in、bury the hatchet、bury alive、bury the lede",
    "surprise": "in surprise、take by surprise、surprise attack、surprise party",
    "mile": "miles away、run for miles、miss by a mile",
}

WORD_FAMILY_DATA = {
    "connect": "connection (n.) 联系 | connected (adj.) 连接的 | disconnect (v.) 断开",
    "block": "blockage (n.) 阻塞 | blocked (adj.) 被封锁的 | blockbuster (n.) 大片",
    "career": "careerist (n.) 野心家 | career-minded (adj.) 事业心强的",
    "client": "clientele (n.) 客户群 | client-server (n.) 客户端-服务器",
    "communicate": "communication (n.) 交流 | communicative (adj.) 健谈的 | communicator (n.) 沟通者",
    "curious": "curiosity (n.) 好奇心 | incurious (adj.) 不好奇的",
    "difference": "different (adj.) 不同的 | differentiate (v.) 区分 | indifferent (adj.) 冷漠的",
    "disappear": "disappearance (n.) 消失 | reappear (v.) 再现",
    "district": "districting (n.) 区域划分 | redistrict (v.) 重新划分",
    "drop": "droplet (n.) 小水滴 | dropout (n.) 退学者 | dripper (n.) 滴漏器",
    "either": "neither (pron.) 两者都不 | either-or (n.) 二选一",
    "exist": "existence (n.) 存在 | existent (adj.) 存在的 | co-exist (v.) 共存",
    "financial": "finance (n./v.) 财务 | financier (n.) 金融家 | financially (adv.) 财政上",
    "guard": "guardian (n.) 监护人 | guarded (adj.) 谨慎的 | safeguard (v.) 保护",
    "let": "letdown (n.) 失望 | letup (n.) 减弱 | outlet (n.) 出口",
    "machine": "machinery (n.) 机械 | mechanic (n.) 技工 | mechanical (adj.) 机械的",
    "matter": "material (n.) 材料 | materialism (n.) 唯物主义 | matter-of-fact (adj.) 实事求是的",
    "owe": "owing (adj.) 欠着的 | owed (adj.) 应得的 | due (adj.) 到期的",
    "police": "policeman (n.) 警察 | policy (n.) 政策 | politics (n.) 政治",
    "private": "privacy (n.) 隐私 | privatization (n.) 私有化 | privately (adv.) 私下地",
    "probably": "probable (adj.) 可能的 | probability (n.) 概率 | improbable (adj.) 不可能的",
    "rat": "ratty (adj.) 破旧的 | rattrap (n.) 捕鼠夹 | rattail (n.) 老鼠尾巴",
    "recognize": "recognition (n.) 认出 | recognizable (adj.) 可辨认的 | unrecognizable (adj.) 无法辨认的",
    "represent": "representation (n.) 代表 | representative (n./adj.) 代表/代表性的 | misrepresent (v.) 歪曲",
    "role": "role-play (v.) 角色扮演 | role model (n.) 榜样 | leading role (n.) 主角",
    "scene": "scenery (n.) 风景 | scenic (adj.) 风景优美的 | behind-the-scenes (adj.) 幕后的",
    "search": "searching (adj.) 锐利的 | searchable (adj.) 可搜索的 | searchlight (n.) 探照灯",
    "security": "secure (adj./v.) 安全的/保护 | insecurity (n.) 不安全 | secured (adj.) 已担保的",
    "service": "serve (v.) 服务 | servant (n.) 仆人 | serviceable (adj.) 可用的 | self-service (n.) 自助",
    "sort": "sortable (adj.) 可排序的 | sorter (n.) 分类者 | assorted (adj.) 各式各样的",
    "target": "targeted (adj.) 定向的 | targetable (adj.) 可定为目标的 | nontarget (adj.) 非目标的",
    "track": "tracker (n.) 追踪者 | trackable (adj.) 可追踪的 | backtrack (v.) 原路返回 | soundtrack (n.) 配乐",
    "trade": "trader (n.) 交易者 | trading (n.) 交易 | trademark (n.) 商标 | trade-off (n.) 权衡",
    "western": "westerner (n.) 西方人 | westernize (v.) 西化 | westernmost (adj.) 最西的",
    "whole": "wholly (adv.) 完全地 | wholesome (adj.) 健康的 | wholehearted (adj.) 全心全意的",
    "active": "action (n.) 行动 | activity (n.) 活动 | activate (v.) 激活 | proactive (adj.) 主动的",
    "direct": "direction (n.) 方向 | directly (adv.) 直接地 | director (n.) 导演 | indirect (adj.) 间接的",
    "escape": "escapee (n.) 逃犯 | inescapable (adj.) 无法逃避的 | escapism (n.) 逃避现实",
    "explain": "explanation (n.) 解释 | explanatory (adj.) 解释性的 | unexplainable (adj.) 无法解释的",
    "forward": "forwarding (n.) 转发 | straightforward (adj.) 直截了当的 | wayward (adj.) 任性的",
    "lead": "leader (n.) 领导 | leadership (n.) 领导力 | leading (adj.) 领先的 | mislead (v.) 误导",
    "lie": "liar (n.) 说谎者 | lying (adj.) 说谎的 | white lie (n.) 善意的谎言",
    "partner": "partnership (n.) 合伙关系 | partnering (n.) 合作 | copartner (n.) 合伙人",
    "piece": "piecemeal (adj.) 零碎的 | piecework (n.) 计件工作 | centerpiece (n.) 核心",
    "pull": "pullover (n.) 套头衫 | pull-up (n.) 引体向上 | pullback (n.) 撤退",
    "report": "reporter (n.) 记者 | reportedly (adv.) 据报道 | unreported (adj.) 未报告的",
    "separate": "separation (n.) 分离 | separably (adv.) 可分离地 | inseparable (adj.) 不可分割的",
    "sight": "insight (n.) 洞察力 | eyesight (n.) 视力 | sightseeing (n.) 观光 | foresight (n.) 远见",
    "unusual": "usually (adv.) 通常 | unusualness (n.) 不寻常 | usual (adj.) 通常的",
    "convince": "convincing (adj.) 令人信服的 | convinced (adj.) 确信的 | unconvincing (adj.) 不令人信服的",
    "innocent": "innocence (n.) 无辜 | innocently (adv.) 天真地 | innocence (n.) 清白",
    "concert": "concerted (adj.) 协调的 | concertmaster (n.) 首席 | concerto (n.) 协奏曲",
    "event": "eventful (adj.) 充满大事的 | eventual (adj.) 最终的 | eventuality (n.) 可能性",
    "tower": "towering (adj.) 高耸的 | towered (adj.) 有塔的 | watchtower (n.) 瞭望塔",
    "rule": "ruler (n.) 统治者 | ruling (n./adj.) 裁决/统治的 | overrule (v.) 否决 | unrule (n.) 混乱",
    "stick": "sticky (adj.) 粘的 | sticker (n.) 贴纸 | stickiness (n.) 粘性 | stuck (adj.) 卡住的",
    "wheel": "wheelchair (n.) 轮椅 | wheeler (n.) 轮车 | wheelhouse (n.) 驾驶室 | freewheel (v.) 自由转动",
    "print": "printer (n.) 打印机 | printing (n.) 印刷 | printable (adj.) 可打印的 | blueprint (n.) 蓝图",
    "hundred": "hundredth (adj.) 第一百的 | hundredfold (adv.) 百倍地 | percentage (n.) 百分比",
    "arrange": "arrangement (n.) 安排 | rearranged (adj.) 重新安排的 | arranger (n.) 安排者",
    "basic": "base (n.) 基础 | basis (n.) 基础 | basically (adv.) 基本上 | basement (n.) 地下室",
    "bury": "burial (n.) 埋葬 | buried (adj.) 被埋葬的 | burying (n.) 埋葬行为",
    "surprise": "surprising (adj.) 令人惊讶的 | surprisingly (adv.) 出人意料地 | unsurprised (adj.) 不吃惊的",
    "mile": "mileage (n.) 里程 | milestone (n.) 里程碑 | miler (n.) 一英里赛跑选手",
}


def load_vocab(path):
    """Load vocabulary list from a text file (one word per line)."""
    with open(path, encoding='utf-8') as f:
        return set(line.strip().lower() for line in f if line.strip())


def get_ipa(word):
    return IPA_DATA.get(word, '/' + word + '/')


def get_meaning(word):
    return MEANING_DATA.get(word, word)


def get_pos(word):
    return POS_DATA.get(word, 'v./n.')


def get_reflection(word):
    return REFLECTION_DATA.get(
        word,
        f'「{word.capitalize()}」是本集台词中的重要词汇，通过上下文理解其含义有助于加深记忆。'
    )


def get_mnemonic(word):
    return MNEMONIC_MAP.get(word, '——')


def get_root(word):
    return ROOT_DATA.get(word, '——')


def get_collocations(word):
    return COLLOCATION_DATA.get(word, '——')


def get_word_family(word):
    return WORD_FAMILY_DATA.get(word, '——')
